name: Storybook CI

on:
  pull_request:
    branches: [develop]
    paths: 
      - 'front-end/**'


  workflow_dispatch:

jobs:
  Storybook-CI-CD:
    runs-on: ubuntu-latest
    env:
      working-directory: ./front-end
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: lts/*

      - name: yarn actions (yaml)
        uses: sergioramos/yarn-actions@v6

      - name: Install dependencies
        run: yarn install
        working-directory: ${{ env.working-directory }}

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: ${{ env.working-directory }}
        id: chromatic

      - name: Get Deployed StorybookUrl
      - run: echo ${{ steps.chromatic.outputs.storybookUrl }} |  sed 's/\/iframe.html$//'  
      
