name: Front-End CI

on:
  push:
    branches: [feature/*]
  pull_request:
    branches: [feature/*]

  workflow_dispatch:

jobs:
  fe-build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./front-end
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: lts/*
          cache: "yarn"
          working-directory: ${{ env.working-directory }}

      - name: install packages
        run: yarn install
        working-directory: ${{ env.working-directory }}

      - name: Build with webpack
        run: yarn build
        working-directory: ${{ env.working-directory }}
